version: 2

sources:
  - name: source_data
    database: WALMART_SOURCE_DB
    schema: BRONZE
    tables:
      - name: DEPARTMENT
      - name: STORES
      - name: FACT

models:
  - name: walmart_date_dim
    description: "Dimension table with date info and isHoliday flag"
  - name: walmart_store_dim
    description: "SCD1 dimension table containing store and department details"
  - name: walmart_fact_table_source
    description: "fact table for view"

